//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sandboxConsole.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadTime
    {
        public int Id { get; set; }
        public int ElapsedTime { get; set; }
        public Nullable<System.DateTime> LoadDateTime { get; set; }
        public string bookmaker { get; set; }
    }
}
